export const PROJECT_FORM = 'PROJECT_FORM'; 
export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const VALIDATE_FORM = 'VALIDATE_FORM';
export const ACTUAL_PROJECT = 'ACTUAL_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const ERROR_PROJECT = 'ERROR_PROJECT';

export const PROJECT_TASKS = 'PROJECT_TASKS';
export const ADD_TASK = 'ADD_TASK'; 
export const VALIDATE_TASK = 'VALIDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const ACTUAL_TASK = 'ACTUAL_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const RESET_TASK = 'RESET_TASK';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE ALERT';

export const SUCCESS_REGISTRATION = 'SUCCESS_REGISTRATION';
export const ERROR_REGISTRATION = 'ERROR_REGISTRATION';
export const GET_USER = 'GET_USER';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';
export const CLOSE_SESSION = 'CLOSE_SESSION';